### ISSUE TITLE
Challenge 04 - Footer section

### ISSUE THREAD

**Issue by fermop** [fermop/Frontend_Mentor#1]
The footer of this challenge goes all the way down if the screen size increases its height.

**Comment by Pulkitxm** [comment]
Can I get assigned? lemme know how to start

**Comment by fermop** [comment]
> Can I get assigned? lemme know how to start

Hi Pulkit!

Of course! If you would like to contribute and fix this issue you have to do the following steps:

1. Fork this repository.
2. Clone the repository.
3. Create a new branch.
You can name the branch however you prefer but I'd like it if you name it something like "Challenge_04-Fixnig_footer_issue"
4. Make necessary changes and commit those changes
In this part I'll thank you if you fix it by going to the CSS file of 04-Single_price_grid_component_master directory and write the last two pieces of code on the body selector:
```
body{
    min-height: 100vh;
    background-color: var(--Light-Gray);
    font-size: 1rem;
    font-family: 'Karla', sans-serif;
    box-sizing: border-box;
    padding: 4em 1.5em;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center; <--
    gap: 1rem;  <--
}
```
5. Push changes to GitHub.
6. Submit your changes for review.

if you have any problems or if you struggle at some point feel free to send me a message to my personal [Facebook acount](https://www.facebook.com/fernando.mojica.758737) or to my Discord account **fermop_**.

**Comment by Pulkitxm** [comment]
Got it about that css alteration , but I am a bit confused there are 7 directories which ones have the footer issue that you mentioned ?
**The footer of this challenge goes all the way down if the screen size increases its height.**

**Comment by fermop** [comment]
> Got it about that css alteration , but I am a bit confused there are 7 directories which ones have the footer issue that you mentioned ? **The footer of this challenge goes all the way down if the screen size increases its height.**

Oh don't worry about them, just focus on the issue of Challenge 4. I made another issue for Challenge 6 so another person who is interested in contributing can contribute :)

**Comment by Pulkitxm** [comment]
Ok and which one of those 7 directories have your issue Pease mention it

**Comment by fermop** [comment]
> Ok and which one of those 7 directories have your issue Pease mention it

The 4th one:
04-Single_price_grid_component_master
